import { pickRandom } from "./utils.ts";
export type Palette = ReturnType<typeof createPalette>;

export function createPalette() {
    //credit: kgolid
    return pickRandom([
        {
            name: "tsu_akasaka",
            colors: [
                "#687f72",
                "#cc7d6c",
                "#dec36f",
                "#dec7af",
                "#ad8470",
                "#424637",
            ],
            stroke: "#251c12",
            background: "#cfc7b9",
            size: 6,
            type: "chromotome",
        },
        {
            name: "present-correct",
            colors: [
                "#fd3741",
                "#fe4f11",
                "#ff6800",
                "#ffa61a",
                "#ffc219",
                "#ffd114",
                "#fcd82e",
                "#f4d730",
                "#ced562",
                "#8ac38f",
                "#79b7a0",
                "#72b5b1",
                "#5b9bae",
                "#6ba1b7",
                "#49619d",
                "#604791",
                "#721e7f",
                "#9b2b77",
                "#ab2562",
                "#ca2847",
            ],
            size: 20,
            type: "chromotome",
        },
        {
            name: "tsu_arcade",
            colors: [
                "#4aad8b",
                "#e15147",
                "#f3b551",
                "#cec8b8",
                "#d1af84",
                "#544e47",
            ],
            stroke: "#251c12",
            background: "#cfc7b9",
            size: 6,
            type: "chromotome",
        },
        {
            name: "giftcard_sub",
            colors: [
                "#FBF5E9",
                "#FF514E",
                "#FDBC2E",
                "#4561CC",
                "#2A303E",
                "#6CC283",
                "#238DA5",
                "#9BD7CB",
            ],
            stroke: "#000",
            background: "#FBF5E9",
            size: 8,
            type: "chromotome",
        },
        {
            name: "five-stars",
            colors: [
                "#f5e8c7",
                "#d9dcad",
                "#cf3933",
                "#f3f4f4",
                "#74330d",
                "#8bb896",
                "#eba824",
                "#f05c03",
            ],
            stroke: "#380c05",
            background: "#ecd598",
            size: 8,
            type: "chromotome",
        },
    ]);
}
